site_name: Subscribie Subscription Website Builder
site_url: https://example.com/
repo_url: https://github.com/Subscribie/documentation
edit_uri: blob/edit/main/docs
site_description: Subscription website builder documentation

nav:
    - 'Hosting': 'http://subscriptionwebsitebuilder.co.uk/'
theme: readthedocs
